/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZC_REP003_GEOSITE_REPORTListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheZC_REP003_GEOSITE_REPORTList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheZC_REP003_GEOSITE_REPORTList.onFilterBar().iCheckFilterField("Site Code");
            Then.onTheZC_REP003_GEOSITE_REPORTList.onFilterBar().iCheckFilterField("Site Name");
            Then.onTheZC_REP003_GEOSITE_REPORTList.onFilterBar().iCheckFilterField("Site Manager");
            Then.onTheZC_REP003_GEOSITE_REPORTList.onFilterBar().iCheckFilterField("Site Type");
            Then.onTheZC_REP003_GEOSITE_REPORTList.onFilterBar().iCheckFilterField("Country");
            Then.onTheZC_REP003_GEOSITE_REPORTList.onFilterBar().iCheckFilterField("Building");
            Then.onTheZC_REP003_GEOSITE_REPORTList.onFilterBar().iCheckFilterField("Street");
            Then.onTheZC_REP003_GEOSITE_REPORTList.onFilterBar().iCheckFilterField("Street1");
            Then.onTheZC_REP003_GEOSITE_REPORTList.onFilterBar().iCheckFilterField("Street2");
            Then.onTheZC_REP003_GEOSITE_REPORTList.onFilterBar().iCheckFilterField("City");
            Then.onTheZC_REP003_GEOSITE_REPORTList.onFilterBar().iCheckFilterField("District");
            Then.onTheZC_REP003_GEOSITE_REPORTList.onFilterBar().iCheckFilterField("Region");
            Then.onTheZC_REP003_GEOSITE_REPORTList.onFilterBar().iCheckFilterField("PostalCode");
            Then.onTheZC_REP003_GEOSITE_REPORTList.onFilterBar().iCheckFilterField("Creation Date");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheZC_REP003_GEOSITE_REPORTList.onTable().iCheckColumns(undefined, {"GeoSiteCode":{"header":"Site Code"},"SiteName":{"header":"Site Name"},"SiteManager":{"header":"Site Manager"},"SiteType":{"header":"Site Type"},"Country":{"header":"Country"},"Building":{"header":"Building"},"Street":{"header":"Street"},"Street1":{"header":"Street1"},"Street2":{"header":"Street2"},"City":{"header":"City"},"District":{"header":"District"},"Region":{"header":"Region"},"PostalCode":{"header":"PostalCode"},"CreationDate":{"header":"Creation Date"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheZC_REP003_GEOSITE_REPORTList.onFilterBar().iExecuteSearch();
            
            Then.onTheZC_REP003_GEOSITE_REPORTList.onTable().iCheckRows();

            When.onTheZC_REP003_GEOSITE_REPORTList.onTable().iPressRow(0);
            Then.onTheZC_REP003_GEOSITE_REPORTObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});