/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ZC_REP003_GEOSITE_REPORTObjectPageObjectPage journey");

        opaTest("Navigate to ZC_REP003_GEOSITE_REPORTObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheZC_REP003_GEOSITE_REPORTList.onFilterBar().iExecuteSearch();

            Then.onTheZC_REP003_GEOSITE_REPORTList.onTable().iCheckRows();
            When.onTheZC_REP003_GEOSITE_REPORTList.onTable().iPressRow(0);

            Then.onTheZC_REP003_GEOSITE_REPORTObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheZC_REP003_GEOSITE_REPORTObjectPage.iCheckSection({ section: "GeneratedFacet1" });
            Then.onTheZC_REP003_GEOSITE_REPORTObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "GeoSiteCode" });
            Then.onTheZC_REP003_GEOSITE_REPORTObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "SiteName" });
            Then.onTheZC_REP003_GEOSITE_REPORTObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "SiteManager" });
            Then.onTheZC_REP003_GEOSITE_REPORTObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "SiteType" });
            Then.onTheZC_REP003_GEOSITE_REPORTObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Country" });
            Then.onTheZC_REP003_GEOSITE_REPORTObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Building" });
            Then.onTheZC_REP003_GEOSITE_REPORTObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Street" });
            Then.onTheZC_REP003_GEOSITE_REPORTObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Street1" });
            Then.onTheZC_REP003_GEOSITE_REPORTObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Street2" });
            Then.onTheZC_REP003_GEOSITE_REPORTObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "City" });
            Then.onTheZC_REP003_GEOSITE_REPORTObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "District" });
            Then.onTheZC_REP003_GEOSITE_REPORTObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "Region" });
            Then.onTheZC_REP003_GEOSITE_REPORTObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "PostalCode" });
            Then.onTheZC_REP003_GEOSITE_REPORTObjectPage.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "CreationDate" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});